export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';

export const PAGES = Object.freeze({
  CART: 'CART',
  FAVORITES: 'FAVORITES',
  HOME: 'HOME',
  HYDRATE_SHOPPING_ITEM_POSTED_BY_OTHER_USERS: 'HYDRATE_SHOPPING_ITEM_POSTED_BY_OTHER_USERS',
  MY_PURCHASES: 'MY_PURCHASES',
  PROFILE: 'PROFILE',
  SEARCH_LANDING: 'SEARCH_LANDING',
  SELL_ON_ETSY: 'SELL_ON_ETSY',
  SHOP_HOME: 'SHOP_HOME',
  SHOPPING_ITEM_OVERVIEW: 'SHOPPING_ITEM_OVERVIEW'
});

export const ADD_ITEM_TO_FAVORITES = 'ADD_ITEM_TO_FAVORITES';
export const GET_SHOPPING_ITEMS_POSTED_BY_USERS = 'GET_SHOPPING_ITEMS_POSTED_BY_USERS';
export const REMOVE_ITEM_FROM_FAVORITES = 'REMOVE_ITEM_FROM_FAVORITES';
export const TOGGLE_USER_SETTINGS_MODAL = 'TOGGLE_USER_SETTINGS_MODAL';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
